### ISSUE TITLE
Dolthub client-side code crashbug

### ISSUE THREAD

**Issue by rl1987** [dolthub/dolthub-issues#460] opened 2023-05-16 14:41 UTC
**Describe the bug and expected behavior**

**To Reproduce (please include link if applicable)**
1. Go to https://www.dolthub.com/repositories/dolthub/transparency-in-pricing/compare/main/og44j11to0n25rd2l0c0jmqpfc1u5qqv
2. Wait a few seconds.
3. Scroll down.
4. See error in Chrome DevTools console.

```
TypeError: Cannot read properties of undefined (reading 'displayValue')
    at 9518-173418f71765eef1.js:1:183722
    at Array.some (<anonymous>)
    at 9518-173418f71765eef1.js:1:183559
    at Array.forEach (<anonymous>)
    at 9518-173418f71765eef1.js:1:183541
    at 9518-173418f71765eef1.js:1:183793
    at 9518-173418f71765eef1.js:1:184031
    at oO (framework-8ea3c61dd4c96877.js:25:84129)
    at uB (framework-8ea3c61dd4c96877.js:25:113200)
    at u (framework-8ea3c61dd4c96877.js:25:107747)
l5 @ framework-8ea3c61dd4c96877.js:25
l.componentDidCatch.n.callback @ framework-8ea3c61dd4c96877.js:25
aH @ framework-8ea3c61dd4c96877.js:25
oY @ framework-8ea3c61dd4c96877.js:25
e @ framework-8ea3c61dd4c96877.js:25
(anonymous) @ framework-8ea3c61dd4c96877.js:25
uO @ framework-8ea3c61dd4c96877.js:25
u_ @ framework-8ea3c61dd4c96877.js:25
r4 @ framework-8ea3c61dd4c96877.js:25
uB @ framework-8ea3c61dd4c96877.js:25
u @ framework-8ea3c61dd4c96877.js:25
x @ framework-8ea3c61dd4c96877.js:49
R @ framework-8ea3c61dd4c96877.js:49
main-dc680205e5a1c51c.js:1 TypeError: Cannot read properties of undefined (reading 'displayValue')
    at 9518-173418f71765eef1.js:1:183722
    at Array.some (<anonymous>)
    at 9518-173418f71765eef1.js:1:183559
    at Array.forEach (<anonymous>)
    at 9518-173418f71765eef1.js:1:183541
    at 9518-173418f71765eef1.js:1:183793
    at 9518-173418f71765eef1.js:1:184031
    at oO (framework-8ea3c61dd4c96877.js:25:84129)
    at uB (framework-8ea3c61dd4c96877.js:25:113200)
    at u (framework-8ea3c61dd4c96877.js:25:107747)
K @ main-dc680205e5a1c51c.js:1
fn @ main-dc680205e5a1c51c.js:1
componentDidCatch @ main-dc680205e5a1c51c.js:1
l.componentDidCatch.n.callback @ framework-8ea3c61dd4c96877.js:25
aH @ framework-8ea3c61dd4c96877.js:25
oY @ framework-8ea3c61dd4c96877.js:25
e @ framework-8ea3c61dd4c96877.js:25
(anonymous) @ framework-8ea3c61dd4c96877.js:25
uO @ framework-8ea3c61dd4c96877.js:25
u_ @ framework-8ea3c61dd4c96877.js:25
r4 @ framework-8ea3c61dd4c96877.js:25
uB @ framework-8ea3c61dd4c96877.js:25
u @ framework-8ea3c61dd4c96877.js:25
x @ framework-8ea3c61dd4c96877.js:49
R @ framework-8ea3c61dd4c96877.js:49
main-dc680205e5a1c51c.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-dc680205e5a1c51c.js:1
fn @ main-dc680205e5a1c51c.js:1
componentDidCatch @ main-dc680205e5a1c51c.js:1
l.componentDidCatch.n.callback @ framework-8ea3c61dd4c96877.js:25
aH @ framework-8ea3c61dd4c96877.js:25
oY @ framework-8ea3c61dd4c96877.js:25
e @ framework-8ea3c61dd4c96877.js:25
(anonymous) @ framework-8ea3c61dd4c96877.js:25
uO @ framework-8ea3c61dd4c96877.js:25
u_ @ framework-8ea3c61dd4c96877.js:25
r4 @ framework-8ea3c61dd4c96877.js:25
uB @ framework-8ea3c61dd4c96877.js:25
u @ framework-8ea3c61dd4c96877.js:25
x @ framework-8ea3c61dd4c96877.js:49
R @ framework-8ea3c61dd4c96877.js:49
/favicon.ico:1     GET https://www.dolthub.com/favicon.ico 404
```

**Screenshots**

![Screenshot 2023-05-16 at 17 40 35](https://github.com/dolthub/dolthub-issues/assets/1080220/4d7ba4aa-090b-4136-8024-e850cde7f5dc)

**Browser info:**
 - Desktop (MacBook Pro M2)
 - OS/Device: macOS
 - Browser: Chrome
 - Version: 112.0.5615.137 (Official Build) (arm64)

**Comment by liuliu-dev** [comment] 2023-05-16 17:16
looking into this today

**Comment by liuliu-dev** [comment] 2023-05-16 22:09
I landed a temporary fix to prevent the website from crashing, and continue investigating the root cause of the issue.

**Closed as completed** 2023-06-01 16:56 UTC
Labels: bug
