### ISSUE TITLE
Unusual query timeout

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolthub-issues#437] opened 2023-04-10 15:01 UTC
**Describe the bug and expected behavior**

I'd like for this query to return, but it times out:

https://www.dolthub.com/repositories/captainstabs/transparency-in-pricing/query/south_baldwin?active=Tables&q=select+*+from+rates+where+hospital_tin+%3D+%2762-1811413%27+order+by+rand%28%29+limit+200%3B

**To Reproduce (please include link if applicable)**

See above.

**Screenshots**
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/16236421/230927778-e8d70909-a9c8-49ff-bfea-bf9e312b3619.png">

**Browser info:**
 - dekstop
 - macOS
 - Firefox
 - 111.01

**Additional context**
When I run this on my dev box I get:

```
(base) ubuntu@ip-10-2-0-167:~/transparency-in-pricing/10$ dolt branch
  main                                          
* south_baldwin                                 
(base) ubuntu@ip-10-2-0-167:~/transparency-in-pricing/10$ time dolt sql -q "select * from rates where hospital_tin = '62-1811413' order by rand() limit 200;"

... results

real    0m0.937s
user    0m0.959s
sys     0m0.160s
```

**Comment by liuliu-dev** [comment] 2024-02-13 21:51
Marking this as closed since the issue cannot be reproduced now.

**Closed as completed by liuliu-dev** 2024-02-13 21:51 UTC
Labels: bug
